"""initial schema

Revision ID: 8bb1b8aa8a55
Revises: 
Create Date: 2026-05-24 19:19:09.886234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '8bb1b8aa8a55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension — must run before any table uses VECTOR type.
    # IF NOT EXISTS: safe to re-run (idempotent).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_alerts',
    sa.Column('application_id', sa.String(length=255), nullable=False),
    sa.Column('drift_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('drift_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('baseline_stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('current_stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_alerts_application_id'), 'drift_alerts', ['application_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('suite_name', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), server_default='api', nullable=False),
    sa.Column('total_cases', sa.Integer(), server_default='0', nullable=False),
    sa.Column('passed_cases', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pass_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('gate_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('gate_result', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_suite_name'), 'eval_runs', ['suite_name'], unique=False)
    op.create_table('llm_logs',
    sa.Column('application_id', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('time_to_first_token_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('otel_trace_id', sa.String(length=32), nullable=True),
    sa.Column('otel_span_id', sa.String(length=16), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_logs_app_created', 'llm_logs', ['application_id', 'created_at'], unique=False)
    op.create_table('metrics',
    sa.Column('application_id', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('total_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('successful_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('avg_latency_ms', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'model', 'period_type', 'period_start', name='uq_metrics_app_model_period')
    )
    op.create_index(op.f('ix_metrics_application_id'), 'metrics', ['application_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('suite_name', sa.String(length=255), nullable=False),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('eval_methods', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('similarity_threshold', sa.Numeric(precision=4, scale=3), server_default='0.850', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_suite_name'), 'test_cases', ['suite_name'], unique=False)
    op.create_table('eval_results',
    sa.Column('eval_run_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('exact_match_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('embedding_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('llm_judge_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('llm_judge_reasoning', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_eval_run_id'), 'eval_results', ['eval_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_results_eval_run_id'), table_name='eval_results')

    op.drop_table('eval_results')
    op.drop_index(op.f('ix_test_cases_suite_name'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_metrics_application_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_llm_logs_app_created', table_name='llm_logs')
    op.drop_table('llm_logs')
    op.drop_index(op.f('ix_eval_runs_suite_name'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_drift_alerts_application_id'), table_name='drift_alerts')
    op.drop_table('drift_alerts')
    # ### end Alembic commands ###
